version: '3.8'
services:
  reverse:
    container_name: reverse
    hostname: reverse
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/ssl/cert.pem:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - app_internal_network
    depends_on:
      - frontend
    image: nginx

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app_internal_network
    depends_on:
      - backend
    image: kleinaitis/gridspace-sift-dashboard-frontend:latest


  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    networks:
      - app_internal_network
    image: kleinaitis/gridspace-sift-dashboard-backend:latest

networks:
  app_internal_network: